import sys
import nbformat
import markdown2
import pdfkit
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter
from jinja2 import Template


def read_notebook(path):
    with open(path, "r", encoding="utf-8") as f:
        return nbformat.read(f, as_version=4)


def generate_toc(markdown_cells):

    toc = "<ul>"

    for md in markdown_cells:

        for line in md.split("\n"):

            if line.startswith("#"):

                level = line.count("#")

                title = line.replace("#", "").strip()

                toc += f"<li style='margin-left:{level*10}px'>{title}</li>"

    toc += "</ul>"

    return toc


def process_notebook(nb):

    html_content = ""
    markdown_cells = []

    formatter = HtmlFormatter(style="colorful", noclasses=True)

    for cell in nb.cells:

        if cell.cell_type == "markdown":

            markdown_cells.append(cell.source)

            html_content += markdown2.markdown(cell.source)

        elif cell.cell_type == "code":

            code_html = highlight(cell.source, PythonLexer(), formatter)

            html_content += f"<h3>Code</h3>{code_html}"

            for output in cell.get("outputs", []):

                if output.output_type == "stream":

                    html_content += f"<div class='output'><pre>{output.text}</pre></div>"

                elif output.output_type == "error":

                    html_content += f"<div class='output'><pre style='color:red'>{''.join(output.traceback)}</pre></div>"

                elif output.output_type == "execute_result":

                    if "text/plain" in output.data:

                        html_content += f"<div class='output'><pre>{output.data['text/plain']}</pre></div>"

                elif output.output_type == "display_data":

                    if "image/png" in output.data:

                        img = output.data["image/png"]

                        html_content += f"<img src='data:image/png;base64,{img}'/>"

    return html_content, markdown_cells


html_template = """
<html>

<head>

<style>

body{
font-family:Arial;
margin:40px;
}

h1,h2,h3{
color:#2c3e50;
}

pre{
background:#f4f4f4;
padding:10px;
border-radius:5px;
}

.output{
background:#eef2f7;
border-left:4px solid #4CAF50;
padding:10px;
margin:10px 0;
}

img{
max-width:100%;
}

.footer{
position:fixed;
bottom:0;
width:100%;
text-align:center;
font-size:12px;
}

</style>

</head>

<body>

<h1>AI Generated Notebook Report</h1>

<h2>Table of Contents</h2>

{{toc}}

{{content}}

<div class="footer">
Generated by nb2pdf Agent
</div>

</body>

</html>
"""


def generate_pdf(html_content, toc):
    template = Template(html_template)
    final_html = template.render(content=html_content, toc=toc)
    
    # Path to wkhtmltopdf.exe
    path_wkhtmltopdf = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
    
    # Tell pdfkit where wkhtmltopdf is
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    
    pdfkit.from_string(final_html, "sample_output.pdf", configuration=config)

def main():

    if len(sys.argv) < 2:

        print("Usage: python nb2pdf_agent.py notebook.ipynb")

        sys.exit(1)

    notebook_file = sys.argv[1]

    nb = read_notebook(notebook_file)

    html_content, markdown_cells = process_notebook(nb)

    toc = generate_toc(markdown_cells)

    generate_pdf(html_content, toc)

    print(" PDF Generated: sample_output.pdf")


if __name__ == "__main__":
    main()